### ISSUE TITLE
Error: undefined method `opt_prefix' for nil

### ISSUE THREAD

**Issue by kjxbyz** [Homebrew/homebrew-test-bot#1440]
https://github.com/insco-inc/homebrew-casks/actions/runs/13951904826/job/39075676927#step:6:1

**Comment by Bo98** [comment]
Looks like a regression from #1410 where it's incorrectly picking up casks and treating them as formulae.

**Comment by SMillerDev** [comment]
That's checking the formulae directory though. What did I miss?

**Comment by Bo98** [comment]
Looks like it now has a check for `tap.cask_file?` but still adds it to `modified_formulae`

**Comment by SMillerDev** [comment]
But that would mean it detects a cask in the formulae directory right?

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/homebrew-test-bot/pull/1410 should be reverted.

**Comment by Bo98** [comment]
Anyhow, the revert should have fixed this now.
